### ISSUE TITLE
test run on codespaces?

### ISSUE THREAD

**Issue by cboettig** [rocker-org/devcontainer-images#17]
Hi @eitsupi 

I was just looking into if I could try to use the updates here in place of @revodavid's original example in https://github.com/revodavid/devcontainers-rstudio (which works but just has minor config issues like the dual user names and default working dir).  Unfortunately I'm not quite understanding the necessary steps. 

I have a demo repo for my course here, which has codespaces enabled.  I created the `devcontainer.json` following the recipe you suggested: https://github.com/espm-157/devcontainers-rstudio/blob/main/.devcontainer/devcontainer.json.  If I understood correctly, this no longer needs the `Dockerfile` and `library-scripts` :file_folder: that we saw in David's example, since those parts would be rolled into the upstream Rocker dockerfile.  

With these changes, I can launch into codespaces and appear to be in a rocker-based container.  However, unlike with David's example, RStudio is not yet running and there is no open port.  If I manually launch RStudio from Codespace's vscode bash terminal, 

```
sudo /usr/lib/rstudio-server/bin/rserver --server-daemonize 0
```

and open port 8787, the link from codespaces forwards me to localhost, which doesn't resolve.  Any ideas what is missing?  Ideally this configuration would mimic the behavior of David's example, with the RStudio session up and running and the port listed in the Ports tab.

**Comment by eitsupi** [comment]
Thanks for taking a look at this!

> the link from codespaces forwards me to localhost, which doesn't resolve. Any ideas what is missing?

Since VSCode does not automatically detect the port, we would need to manually configure port forwarding.

![image](https://user-images.githubusercontent.com/50911393/191482384-cb92b369-997d-491f-a255-62d1961e9890.png)

Perhaps detailed instructions should be posted on the website.......

**Comment by cboettig** [comment]
hmm... I think in @repodavid's example vscode devcontainer does automatically configure the port though.  Digging back into David's example, I realized I was missing this block:

https://github.com/espm-157/devcontainers-rstudio/blob/main/.devcontainer/devcontainer.json#L20-L27 

```
"forwardPorts": [8787],
	"portsAttributes": {
		"8787": {
			"label": "Rstudio",
			"requireLocalPort": true,
			"onAutoForward": "ignore"
		}
	},
	// Use 'postCreateCommand' to run commands after the container is created.
	"postCreateCommand": "sudo rstudio-server start",
  ```
  
  which I think handles the port setup.  Unfortunately I still don't seem to be getting into RStudio from there.  I think I need to change the default protocol to https, not sure what the port attribute is for that?
  
Changing it over to https, this works, I can get into RStudio.  Rstudio is still starting up in `/workspaces` rather than  with an active project matching the corresponding repo though.  


You should be able to run this too by launching a codespace from https://github.com/espm-157/devcontainers-rstudio, thanks to GitHub's generous policy for educators I think anyone can launch a free tiny-VM codespace from there(?).

**Comment by cboettig** [comment]
(hmm, also getting a lot of 502 errors rather than functional codespace... may be an unrelated issue)

**Comment by eitsupi** [comment]
@cboettig I have tried Codespaces on https://github.com/espm-157/devcontainers-rstudio/commit/7b2d69ce2e23735e0a30021e8d3e66c3672b21e7
RStudio was in the following state from the beginning in the browser.

![image](https://user-images.githubusercontent.com/50911393/191782682-eabed1e1-db5c-4be2-acaa-079227c9621b.png)

As far as I have tried, the port attribute must be set to Public in order to view RStudio.
(This is definitely a security issue, but fortunately the URL seems to be randomly generated.)

![image](https://user-images.githubusercontent.com/50911393/191783205-d2b8dd7c-534b-4fa9-a982-ec26dacc3190.png)

> Rstudio is still starting up in `/workspaces` rather than with an active project matching the corresponding repo though.

This is the intended behavior.
It is set in the following line.

https://github.com/rocker-org/devcontainer-images/blob/e1775a0031cb5ad6d2cb32b9eeaefa00e0988825/src/r-ver/assets/rstudio-prefs.json#L6

As far as I have looked, setting up RStudio to open a workspace that is set to an arbitrary directory name from the start would require quite a hack and doesn't seem practical.

**Comment by cboettig** [comment]
Thanks for testing this @eitsupi !  

Okay it's a pity about not being able to start RStudio in the right project, does seem like it could be done (since RStudio knows how to resume the last open project, but I haven't dug enough in the config files).  

The port-forwarding bit appears a bit buggy to me, sometimes it seems to work just fine, but sometimes I get a 502 Bad Gateway error, and sometimes am just sent to https://localhost:8787 instead, which obviously doesn't work.   I think the 502 error always happens if the codespace already exists but has shut down, RStudio appears to no longer be running.  Maybe we need some sort of resume command.  

I think I am getting a private https port by default now:

![image](https://user-images.githubusercontent.com/222586/192127091-8e87b752-ebba-4b64-aa5e-c8941e742493.png)

and this seems to work fine -- I don't have to set it to public to successfully open the port.  Anyway, this definitely feels like progress, and the codespace starts much faster with these pre-built containers than with the earlier setup.  I'll keep testing to see if I can get a better handle on the possible connection issues.

**Comment by eitsupi** [comment]
Actually I don't use Codespaces or RStudio (I usually use VSCode Remote-Containers on my computer), so I haven't delved into why I had to make the port public in my environment.

> Maybe we need some sort of resume command.

`sudo rstudio-server start` is not enough?
I think `postCreateCommand` is just automatically executing commands that users run after container creation.
(Runs only once after the container is created)

For example, here it is used to install the javascript package.

https://github.com/rocker-org/devcontainer-images/blob/5749095c9c70c715ea68817f6c6f3618deb31861/.devcontainer/devcontainer.json#L22

**Comment by eitsupi** [comment]
> Maybe we need some sort of resume command.

It looks like `postStartCommand` and `postAttachCommand` are there for this purpose (but I've never used them)
https://containers.dev/implementors/spec/#environment-resume

**Comment by cboettig** [comment]
ah, thanks! that looks perfect, I'll try that out.  

Clearly I need to spend a bit more time familiarizing myself with the spec.

**Comment by eitsupi** [comment]
I tried it on VSCode and `postAttachCommand` worked well for this use.

**Comment by eitsupi** [comment]
I have made a PR revodavid/devcontainers-rstudio#6 as a demonstration of images from this repo.

**Comment by eitsupi** [comment]
Now that revodavid/devcontainers-rstudio#6 has been merged, close this.
