### ISSUE TITLE
Publication on the devcontainer official website

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/devcontainer-images#18]
At this time, only devcontainer featuers are listed on the official website (https://containers.dev/collections), but it is expected that the devcontainer template will be available in the future. (devcontainers/spec#98)

Those listed on the official site will be selectable from Codespaces and others, and users will be able to use the definitions easily without knowing them in advance.

**Comment by eitsupi** [comment]
I would like to create a feature that installs R first.
[As Ruby is installed via rvm in the existing feature](https://github.com/devcontainers/features/blob/ceb4544cc38d4882a0294c79f4ef8123435cb027/src/ruby/README.md), perhaps R is suitable to be installed via [rig](https://github.com/r-lib/rig) (it is difficult to install R on Ubuntu arm64 without using rig.)

And, one reason is that the devcontainer images will hold metadata for installed features (devcontainers/spec#95), so I want the R-installed containers that we build in this repository to have metadata for the features that install R.
Like this https://github.com/devcontainers/images/blob/4690ca1ee6b0ea5c3bef39b14e46c0c33d01824f/src/ruby/.devcontainer/devcontainer.json#L14

@cboettig @eddelbuettel Can I create a repository like `rocker-org/devcontainer-featuers` using the template?
https://github.com/devcontainers/feature-template
If we were to maintain a featuer to install R to easily build multilingual containers that include R, the Rocker project would be the best place.

**Comment by eitsupi** [comment]
> Why? Unix is Unix. `configure; make; make install` and/or package managers still exist not matter flavor the cpu has.

Sorry, I left out the explanation about the installation time.
I thought the installer installation would take precedence over the source installation, since the feature installation is performed locally by the user.

I suppose it is possible to create a feature that falls back to a src installation, as planned here in Python, but I just wanted to start with a simple method.
devcontainers/features#75

**Comment by cboettig** [comment]
this sounds good to me!

**Comment by eddelbuettel** [comment]
> with a simple method

By all means. 

But by a quick scan this appears to be build on Ubuntu where we have R either i) from the distro (maybe dated), ii) from the CRAN backport (current version, widely used, my fave too) or iii) or as always from source.  Now (and I am 100% naive here as I have not looked at it in any detail) where does `rig` come in, and what is better with it?  From what I can gather it allows yet another package management layer _outside the system package management layer_.  I am sure there are use case for that for some people but is devcontainters one? Or would, say, `r2u` be an alternative as it brings all R packages back to the _system package management_ layer?

**Comment by eitsupi** [comment]
> what is better with it?

Good point.
I see two advantages of rig.

1. Easily install any version of R. (I wanted to start with as simple an installation script as possible.)
2. Supports arm64 version of Ubuntu. `rig` installs the arm64 version of R uploaded here. https://github.com/r-hub/R/releases/tag/v4.2.1

In fact, I have very little experience with rig, so there is a possibility that it will not work well and I will give up on this direction.

> I am sure there are use case for that for some people but is devcontainters one? Or would, say, `r2u` be an alternative as it brings all R packages back to the _system package management_ layer?

Of course there is no need for one, and I think r2u and bspm configured containers are useful in quite a few use cases.
I have already opened #5 as a backlog as I would like to add it here.
(The reason I have not added it so far and only build `rocker/tidyvese` based containers is that I am not yet familiar with the devcontainer cli and am not sure what configuration would be better.)

A feature to configure the bspm is also likely to be useful and could be added in the future.

**Comment by eitsupi** [comment]
After writing a script that uses rig to install R, I came to think it seems feasible to provide an optional way to install R.
https://github.com/rocker-org/devcontainer-features/blob/e4d1dd7cd8dbd5be96384ddba1423477256fa900/src/r-rig/install.sh

**Comment by eitsupi** [comment]
The template for VSCode has been updated to comply with the spec proposal.
For now, this template proposes three base images, `rocker/r-ver`, `rocker/tidyverse`, and `rocker/geospacial`.

https://github.com/microsoft/vscode-dev-containers/blob/ecb28cdcf443603ec8f037afff85c63c8cd1dc95/containers/r/devcontainer-template.json#L21-L30

Since [Jupyter can now be installed with the feature](https://github.com/rocker-org/devcontainer-features/blob/fed25ea54be9fadc789b1eea0f0b5748ca9bea17/src/r-rig/README.md) and there is no need to stick to `rocker/binder`, I would like to prepare three base images, `rocker/r-ver` base, `rocker/tidyverse` base, and `rocker/geospacial`, first.
Users can easily set up Jupyter by using the feature, so no upstream installation is required.

**Comment by cboettig** [comment]
nice, sounds great!

**Comment by eitsupi** [comment]
Done by devcontainers/devcontainers.github.io#36 and devcontainers/devcontainers.github.io#49
